### ISSUE TITLE
Web app issue

### ISSUE THREAD

**Issue by nozge** [circuitdiagram/circuitdiagram#31] opened 2021-01-17 22:31 UTC
Hello i already downloaded the code 
But when i start i missed some reference 
System.drawing ** 

Can  u please tell me how to set up in my own website ?
Tell me in steps thank you very much

**Comment by SamuelFisher** [comment] 2021-01-18 18:11
Duplicate of #30.

**Closed as completed by SamuelFisher** 2021-01-18 18:11 UTC
